---
title: "Analyses of 27 years of stand structure development and basal area growth response to a range of initial basal area density levels, 1992-2019 "
author: "Michael Jull and Hardy Griesbauer"
date: "`r Sys.Date()`"

site: bookdown::bookdown_site

output:
  bookdown::word_document2:
    toc: yes

 


        
        
---

```{r setup,echo = FALSE}

knitr::opts_chunk$set(echo = FALSE,message=FALSE,warning=FALSE)

# To render:
# bookdown::render_book ("index.Rmd")

# If you want to render to website, use this in the YAML:
# Remember to indent!

# documentclass: book
# output:
#   bookdown::gitbook: 
#     config:
#       toc:
#         collapse: none

# If you want to render to word, use this in the YAML
# output:
#   bookdown::word_document2:
#     toc: yes

```


# Preamble

I've organized our manuscript into the sections as outlined on the table of contents on the left side of the screen. A few notes:

- There are a lot of figures and data.  To review this manuscript, it might be easiest to use the links on the left to navigate through the sections. 
- You will see that some of the figures are labelled "figure" or "appendix", depending on where I think they might end up in the final manuscript.  Easy to change this though!

## Main results and conclusions to focus on
*From a previous e-mail thread:*
3 main elements: (a) influence of residual BA on stand and tree level response, (b) the fact that this is a long-term (27-year) dataset of stand response in a randomized and replicated set of treatments - i.e. - not ad hoc and not retropective - and (c) the species question - response of subalpine fir and spruce. Further, it is a relatively unique trial for this kind of forest type, asking core questions about stand response.


## To-Do list

- Finalize the title.  Based on previous discussions, the title should refer to: (i) spruce-fir forests, (ii) basal area or growth response to basal area treatments, and (iii) this is an unven-aged stand.  Does the title "Analyses of 27-year growth and stand development responses to partial harvest in an uneven-aged spruce-fir stand" get close?
- How to refer to treatment units?  For some reason, I like the idea of referring to "high-removal", "low-removal", but we also discussed "high residual basal area (high RBA)" and "low residual basal area (low RBA)".  Once we decide on this, it will be easy to make changes throughout the document.
- Start to whittle down figures/tables


